# Generated by Django 3.1.2 on 2020-10-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201023_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=200, null=True)),
                ('ciudad', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(max_length=200, null=True)),
                ('cp', models.CharField(max_length=200, null=True)),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.cliente')),
                ('envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.envio')),
            ],
        ),
    ]
