# Generated by Django 3.1.2 on 2020-10-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetosenvio',
            name='envio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.envio'),
        ),
    ]
